//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradaran
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grqer
    {
        public int id { get; set; }
        public string vernagir { get; set; }
        public string heghinak { get; set; }
        public Nullable<int> gin { get; set; }
        public Nullable<int> qanak { get; set; }
    }
}
